### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by bestouff** [michaelsproul/rust-sequence-trie#12]
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:31: 287:39 error: type `&'static str` does not implement any method in scope named `fmt`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287         try!("Trie { value: ".fmt(fmt));
                                                                                                                           ^~~~~~~~
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: methods from traits can only be called if the trait is in scope; the following traits are implemented but not in scope, perhaps add a `use` for one of them:
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #1: use `core::fmt::Show`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #2: use `core::fmt::Debug`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #3: use `core::fmt::Display`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #4: use `core::fmt::Octal`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #5: use `core::fmt::Binary`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #6: use `core::fmt::LowerHex`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #7: use `core::fmt::UpperHex`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #8: use `core::fmt::Pointer`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #9: use `core::fmt::LowerExp`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:287:39: 287:39 help: candidate #10: use `core::fmt::UpperExp`
/home/xav/.cargo/registry/src/github.com-1ecc6299db9ec823/sequence_trie-0.0.5/src/lib.rs:288:25: 288:33 error: type `core::option::Option<V>` does not implement any method in scope named `fmt`

(continued, but I think it's ebough)

**Comment by michaelsproul** [comment]
Ah! Thanks for the catch! I fixed this yesterday with the 0.0.6 release but forgot to push it to the registry!

Should be fixed now if you run `cargo update` :smile:

**Comment by bestouff** [comment]
Works well, thanks !
